### ISSUE TITLE
Load navmesh from .bin?

### ISSUE THREAD

**Issue by pacarevolution** [arl/go-detour#29]
Hello!! And Thanks for this awesome library. I hope I can implement this in my project!

Is there any way to load a Recast Navmesh from a .bin file?
I want to use detour to get some walkable paths for my game.

Thanks!!

**Comment by arl** [comment]
Hi, thank you.
When I've implemented this, it was possible to read Detour navigation meshes with 
https://github.com/arl/go-detour/blob/master/detour/mesh.go#L68.
Don't know if the format has evolved and I haven't tried recently, but recent navmeshes may be backward compatible.

this project needs a bit of love (documentation is not showing at the moment on https://pkg.go.dev/github.com/arl/go-detour due to the LICENSE not being recognized. I'll have to fix that.
@pacarevolution
